/*
* Tweet Controller allows for gathering tweets directly
*/
angular.module('tweets', ['globalMethods', 'globalData','service_twitter'])
.controller('TweetsController', function ($scope, StoredData, GlobalMethods,Twitter) {
  $scope.data = {

    tweets: StoredData.tweets,
    trendingCities: StoredData.trendingCities,
    test:StoredData
  };
  $scope.getTweets = GlobalMethods.getTweets;
  $scope.getTrendingCities = GlobalMethods.getTrendingCities; 
});


// var tweet = { metadata: { iso_language_code: 'en', result_type: 'recent' },
//     created_at: 'Sun Oct 26 03:51:21 +0000 2014',
//     id: 526219507556446200,
//     id_str: '526219507556446208',
//     text: 'RT @_olivviamarie: 10-4 GIANTS ARE ON 🔥🔥🔥👏👏',
//     source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
//     truncated: false,
//     in_reply_to_status_id: null,
//     in_reply_to_status_id_str: null,
//     in_reply_to_user_id: null,
//     in_reply_to_user_id_str: null,
//     in_reply_to_screen_name: null,
//     user: 
//      { id: 55367379,
//        id_str: '55367379',
//        name: '▼',
//        screen_name: 'RosieOMG',
//        location: 'fangirling',
//        profile_location: null,
//        description: 'Everything happens for a reason!',
//        url: 'http://t.co/BELZN1d2Gf',
//        entities: [Object],
//        protected: false,
//        followers_count: 466,
//        friends_count: 153,
//        listed_count: 3,
//        created_at: 'Thu Jul 09 21:25:02 +0000 2009',
//        favourites_count: 5326,
//        utc_offset: -14400,
//        time_zone: 'Eastern Time (US & Canada)',
//        geo_enabled: false,
//        verified: false,
//        statuses_count: 35593,
//        lang: 'en',
//        contributors_enabled: false,
//        is_translator: false,
//        is_translation_enabled: false,
//        profile_background_color: '1180F0',
//        profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/435109925358800896/cAjqr642.jpeg',
//        profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/435109925358800896/cAjqr642.jpeg',
//        profile_background_tile: true,
//        profile_image_url: 'http://pbs.twimg.com/profile_images/521784557486350337/tHAMkJet_normal.png',
//        profile_image_url_https: 'https://pbs.twimg.com/profile_images/521784557486350337/tHAMkJet_normal.png',
//        profile_banner_url: 'https://pbs.twimg.com/profile_banners/55367379/1411514737',
//        profile_link_color: '03B8E6',
//        profile_sidebar_border_color: '000000',
//        profile_sidebar_fill_color: 'D8E0E6',
//        profile_text_color: '2FBDD6',
//        profile_use_background_image: true,
//        default_profile: false,
//        default_profile_image: false,
//        following: false,
//        follow_request_sent: false,
//        notifications: false },
//     geo: null,
//     coordinates: null,
//     place: null,
//     contributors: null,
//     retweeted_status: 
//      { metadata: [Object],
//        created_at: 'Sun Oct 26 03:32:20 +0000 2014',
//        id: 526214718927556600,
//        id_str: '526214718927556608',
//        text: '10-4 GIANTS ARE ON 🔥🔥🔥👏👏',
//        source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
//        truncated: false,
//        in_reply_to_status_id: null,
//        in_reply_to_status_id_str: null,
//        in_reply_to_user_id: null,
//        in_reply_to_user_id_str: null,
//        in_reply_to_screen_name: null,
//        user: [Object],
//        geo: null,
//        coordinates: null,
//        place: null,
//        contributors: null,
//        retweet_count: 2,
//        favorite_count: 2,
//        entities: [Object],
//        favorited: false,
//        retweeted: false,
//        lang: 'en' },
//     retweet_count: 2,
//     favorite_count: 0,
//     entities: { hashtags: [], symbols: [], urls: [], user_mentions: [Object] },
//     favorited: false,
//     retweeted: false,
//     lang: 'en' }
